#!/usr/bin/env python3
"""Build the "rendered MAESTRO" bench corpus: real piano performances, real timing, real
velocities, real sustain pedal, rendered to audio through a sampled piano, with exact ground
truth. This is the real counterpart to tools/bench/make_corpus.py's synthetic cases: same
<name>.wav / <name>.mid contract, but the notes were actually played by a person on a Disklavier,
not generated by a formula.

Requires the cache tools/bench/fetch_maestro.py fills: the MAESTRO v3 MIDI tree and its metadata
CSV, a FluidSynth build, and a piano SoundFont. Run that first.

What this does:

  1. Reads maestro-v3.0.0.csv, keeps split == "test" (performances the transcription engine has
     never had a chance to overfit to indirectly, unlike train/validation).
  2. For each one, computes pedal density: the fraction of the performance's duration where
     CC64 (sustain) is at or above 64. Stratifies into low (< 10%), mid (10-50%), high (> 50%)
     pedal use, so the corpus exercises dry passages and heavily-blurred ones alike.
  3. Deterministically (sorted by filename, one fixed-seed RNG consumed in a fixed order) picks
     up to 8 performances per bucket, and a 30-second excerpt from each with at least 20 note
     onsets in it.
  4. Ground truth <name>.mid: notes whose onset falls inside the excerpt window, original
     velocities, offsets pedal-extended (a note released while the pedal is down keeps sounding,
     on paper, until the pedal next lifts) and clipped to the window end. Also carries the
     window's own CC64 stream: one synthetic event at t=0 with the pedal state at window start
     (so a window that opens mid-pedal is represented), plus every real CC64 event that falls
     inside the window, times relative to window start. Bench.cpp reads note-level ground truth
     straight off note-on/note-off pairs, and pedal ground truth straight off these CC64 events.
  5. Rendered audio <name>.wav: the same window rendered by FluidSynth from the *original*
     MIDI (including its CC64, so the real pedal produces the real ring, rather than us faking
     it), gain-adjusted so the window's peak sits just under -1 dBFS without clipping.

Usage:  tools/bench/.venv/Scripts/python.exe tools/bench/make_real_corpus.py [output-dir]
"""

import argparse
import bisect
import csv
import hashlib
import math
import os
import pathlib
import random
import subprocess
import sys
import tempfile
import wave

import pretty_midi

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
CACHE_DIR = pathlib.Path(os.environ.get("USERPROFILE", str(pathlib.Path.home()))) / ".okstudio" / "maestro-cache"
MAESTRO_ROOT = CACHE_DIR / "maestro-v3.0.0"
MAESTRO_CSV = MAESTRO_ROOT / "maestro-v3.0.0.csv"
DEFAULT_OUTPUT = REPO_ROOT / "Tests" / "bench_corpus_maestro"

# Fixed so the corpus is exactly reproducible: same 24 performances, same 24 windows, every time,
# as long as the upstream MAESTRO/FluidSynth/SoundFont files are the ones fetch_maestro.py pinned.
SEED = 20260818

WINDOW_SECONDS = 30.0
MIN_ONSETS = 20
PER_BUCKET = 8
SAMPLE_RATE = 44100
TARGET_PEAK_DBFS = -1.0
# Rendered loud-to-quiet; the first one whose window peak lands at or under TARGET_PEAK_DBFS wins.
# Deliberately starts well above what a first pass at 1.0 typically needs, so busy fortissimo
# chords (the case most likely to clip) still get a real re-render rather than a hopeful guess.
GAIN_CANDIDATES = [3.0, 2.0, 1.2, 0.7, 0.4, 0.22, 0.12]

LOW_PEDAL_MAX = 0.10
HIGH_PEDAL_MIN = 0.50
BUCKET_NAMES = ("low", "mid", "high")


def find_one(root, name_suffix):
    for path in root.rglob(f"*{name_suffix}"):
        return path
    raise SystemExit(f"could not find *{name_suffix} under {root}; run tools/bench/fetch_maestro.py first")


FLUIDSYNTH_EXE = find_one(CACHE_DIR / "fluidsynth", "fluidsynth.exe")
SOUNDFONT = find_one(CACHE_DIR / "soundfont", ".sf2")


# --- pedal-state helpers --------------------------------------------------------------------


def merged_cc64(pm):
    events = sorted(
        ((cc.time, cc.value) for inst in pm.instruments for cc in inst.control_changes if cc.number == 64),
        key=lambda e: e[0],
    )
    return events


def pedal_density(cc64_events, duration):
    """Fraction of [0, duration) where the sustain pedal reads at or above 64 (down)."""
    if duration <= 0:
        return 0.0
    down_time = 0.0
    prev_t = 0.0
    prev_val = 0  # MIDI's implicit pedal-up default before any CC64 message
    for t, v in cc64_events:
        if t > prev_t and prev_val >= 64:
            down_time += t - prev_t
        prev_t = max(prev_t, t)
        prev_val = v
    if duration > prev_t and prev_val >= 64:
        down_time += duration - prev_t
    return down_time / duration


def pedal_value_at(cc64_events, times, t):
    idx = bisect.bisect_right(times, t)
    return cc64_events[idx - 1][1] if idx > 0 else 0


def next_pedal_release_after(cc64_events, times, t):
    idx = bisect.bisect_right(times, t)
    for et, ev in cc64_events[idx:]:
        if ev < 64:
            return et
    return None


# --- survey: one lightweight pass over every test-split performance ------------------------


class Candidate:
    __slots__ = ("midi_filename", "audio_filename", "year", "duration", "density")

    def __init__(self, midi_filename, audio_filename, year, duration, density):
        self.midi_filename = midi_filename
        self.audio_filename = audio_filename
        self.year = year
        self.duration = duration
        self.density = density


def survey_test_split():
    with open(MAESTRO_CSV, encoding="utf-8") as f:
        rows = [row for row in csv.DictReader(f) if row["split"] == "test"]
    rows.sort(key=lambda r: r["midi_filename"])

    candidates = []
    for i, row in enumerate(rows):
        midi_path = MAESTRO_ROOT / row["midi_filename"]
        pm = pretty_midi.PrettyMIDI(str(midi_path))
        duration = pm.get_end_time()
        density = pedal_density(merged_cc64(pm), duration)
        candidates.append(Candidate(row["midi_filename"], row["audio_filename"], row["year"], duration, density))
        if (i + 1) % 40 == 0 or i + 1 == len(rows):
            print(f"  surveyed {i + 1}/{len(rows)} test performances")
    return candidates


def stratify(candidates):
    def classify(density, low_max, high_min):
        if density < low_max:
            return "low"
        if density > high_min:
            return "high"
        return "mid"

    low_max, high_min = LOW_PEDAL_MAX, HIGH_PEDAL_MIN
    buckets = {name: [] for name in BUCKET_NAMES}
    for c in candidates:
        buckets[classify(c.density, low_max, high_min)].append(c)

    empty = [name for name in BUCKET_NAMES if not buckets[name]]
    if empty:
        # Fall back to tertiles of the observed distribution so every bucket gets something,
        # rather than silently shipping a corpus with a hole in it.
        densities = sorted(c.density for c in candidates)
        low_max = densities[len(densities) // 3]
        high_min = densities[(2 * len(densities)) // 3]
        buckets = {name: [] for name in BUCKET_NAMES}
        for c in candidates:
            buckets[classify(c.density, low_max, high_min)].append(c)
        print(
            f"  note: default pedal-density bounds left {empty} empty; "
            f"fell back to tertile bounds low<{low_max:.3f}, high>{high_min:.3f}"
        )

    for name in BUCKET_NAMES:
        print(f"  bucket {name}: {len(buckets[name])} candidates")
    return buckets


# --- excerpt selection + ground truth --------------------------------------------------------


def pick_excerpt_start(notes_start_times, duration, rng):
    """Deterministically (given rng's state) find a WINDOW_SECONDS start with >= MIN_ONSETS
    onsets inside it. Tries random offsets first (so the corpus isn't just "the first 30s of
    every piece"), then falls back to a full grid scan so a qualifying window is always found
    if one exists.
    """
    margin = 5.0
    lo, hi = margin, duration - WINDOW_SECONDS - margin
    if hi <= lo:
        lo, hi = 0.0, max(0.0, duration - WINDOW_SECONDS)

    def onset_count(start):
        end = start + WINDOW_SECONDS
        lo_i = bisect.bisect_left(notes_start_times, start)
        hi_i = bisect.bisect_left(notes_start_times, end)
        return hi_i - lo_i

    for _ in range(200):
        start = rng.uniform(lo, hi) if hi > lo else lo
        if onset_count(start) >= MIN_ONSETS:
            return start

    step = 1.0
    start = 0.0
    while start + WINDOW_SECONDS <= duration:
        if onset_count(start) >= MIN_ONSETS:
            return start
        start += step
    return None


def build_ground_truth(notes, cc64_events, cc64_times, start, end):
    gt_notes = []
    for n in notes:
        if not (start <= n.start < end):
            continue
        raw_offset = n.end
        if pedal_value_at(cc64_events, cc64_times, raw_offset) >= 64:
            release = next_pedal_release_after(cc64_events, cc64_times, raw_offset)
            eff_offset = release if release is not None else end
        else:
            eff_offset = raw_offset
        eff_offset = min(eff_offset, end)
        eff_offset = max(eff_offset, n.start + 0.005)
        gt_notes.append((n.start - start, eff_offset - start, n.pitch, n.velocity))
    gt_notes.sort(key=lambda t: (t[0], t[2]))
    return gt_notes


def build_ground_truth_pedal(cc64_events, cc64_times, start, end):
    """The window's own CC64 stream, times relative to window start: one synthetic event at t=0
    carrying the pedal state at window start (so a window that opens mid-pedal is represented even
    though nothing actually fired inside it), plus every real CC64 event strictly inside the
    window. An event landing exactly on `start` is already captured by the synthetic t=0 one, so
    it is not duplicated.
    """
    gt_pedal = [(0.0, pedal_value_at(cc64_events, cc64_times, start))]
    for t, v in cc64_events:
        if start < t < end:
            gt_pedal.append((t - start, v))
    gt_pedal.sort(key=lambda e: e[0])
    return gt_pedal


def write_ground_truth_midi(path, gt_notes, gt_pedal=()):
    pm = pretty_midi.PrettyMIDI(resolution=10000, initial_tempo=120.0)
    inst = pretty_midi.Instrument(program=0, name="piano")
    for onset, offset, pitch, velocity in gt_notes:
        inst.notes.append(pretty_midi.Note(velocity=int(velocity), pitch=int(pitch), start=onset, end=offset))
    for time, value in gt_pedal:
        inst.control_changes.append(pretty_midi.ControlChange(number=64, value=int(value), time=time))
    pm.instruments.append(inst)
    pm.write(str(path))


# --- rendering ---------------------------------------------------------------------------------


def build_render_source(notes, all_ccs, all_bends, end):
    """A PrettyMIDI object holding everything up to `end`, unmodified: this is what gets
    rendered, and the real CC64 sweep in it is what makes a pedal-held note ring the way the
    ground truth's offset extension only approximates on paper.
    """
    pm = pretty_midi.PrettyMIDI(resolution=10000, initial_tempo=120.0)
    inst = pretty_midi.Instrument(program=0, name="piano")
    for n in notes:
        if n.start < end:
            inst.notes.append(pretty_midi.Note(velocity=n.velocity, pitch=n.pitch, start=n.start, end=n.end))
    for cc in all_ccs:
        if cc.time < end:
            inst.control_changes.append(pretty_midi.ControlChange(number=cc.number, value=cc.value, time=cc.time))
    for pb in all_bends:
        if pb.time < end:
            inst.pitch_bends.append(pretty_midi.PitchBend(pitch=pb.pitch, time=pb.time))
    # Sentinel: forces the file (and so the render) to run through exactly `end`, even if the
    # last real event in the window is earlier and would otherwise leave FluidSynth nothing to
    # render out to the boundary. Value 0 is harmless here: the window gets sliced off exactly
    # at `end` afterwards, so this event's effect on the sound is never actually heard.
    inst.control_changes.append(pretty_midi.ControlChange(number=64, value=0, time=end))
    pm.instruments.append(inst)
    return pm


def render_window(render_pm, start, end, gain, work_dir):
    midi_path = work_dir / "render.mid"
    wav_path = work_dir / "render.wav"
    render_pm.write(str(midi_path))
    if wav_path.exists():
        wav_path.unlink()

    result = subprocess.run(
        [str(FLUIDSYNTH_EXE), "-ni", "-F", str(wav_path), "-r", str(SAMPLE_RATE), "-g", str(gain), str(SOUNDFONT), str(midi_path)],
        capture_output=True,
        text=True,
        timeout=120,
    )
    if result.returncode != 0 or not wav_path.exists():
        raise RuntimeError(f"fluidsynth failed (code {result.returncode}):\n{result.stdout}\n{result.stderr}")

    with wave.open(str(wav_path), "rb") as w:
        channels = w.getnchannels()
        sampwidth = w.getsampwidth()
        assert sampwidth == 2, f"expected 16-bit PCM, got {sampwidth * 8}-bit"
        frames = w.readframes(w.getnframes())

    import array

    samples = array.array("h")
    samples.frombytes(frames)

    start_frame = round(start * SAMPLE_RATE)
    window_frames = round(WINDOW_SECONDS * SAMPLE_RATE)
    start_idx = start_frame * channels
    want = window_frames * channels

    window = samples[start_idx : start_idx + want]
    if len(window) < want:
        window = window + array.array("h", [0]) * (want - len(window))

    peak = max((abs(s) for s in window), default=0)
    peak_dbfs = 20 * math.log10(peak / 32768.0) if peak > 0 else float("-inf")

    return window, channels, peak_dbfs


def write_wav(path, samples, channels):
    with wave.open(str(path), "wb") as w:
        w.setnchannels(channels)
        w.setsampwidth(2)
        w.setframerate(SAMPLE_RATE)
        w.writeframes(samples.tobytes())


# --- driving it all ------------------------------------------------------------------------


def process_case(name, midi_filename, audio_filename, rng, work_dir, output_dir, render=True):
    pm = pretty_midi.PrettyMIDI(str(MAESTRO_ROOT / midi_filename))
    notes = sorted((n for inst in pm.instruments for n in inst.notes), key=lambda n: n.start)
    all_ccs = sorted((cc for inst in pm.instruments for cc in inst.control_changes), key=lambda c: c.time)
    all_bends = sorted((pb for inst in pm.instruments for pb in inst.pitch_bends), key=lambda p: p.time)
    cc64_events = [(cc.time, cc.value) for cc in all_ccs if cc.number == 64]
    cc64_times = [t for t, _ in cc64_events]
    duration = pm.get_end_time()

    note_starts = [n.start for n in notes]
    start = pick_excerpt_start(note_starts, duration, rng)
    if start is None:
        print(f"  skipping {name}: no {WINDOW_SECONDS:.0f}s window with >= {MIN_ONSETS} onsets in {midi_filename}")
        return None
    end = start + WINDOW_SECONDS

    gt_notes = build_ground_truth(notes, cc64_events, cc64_times, start, end)
    gt_pedal = build_ground_truth_pedal(cc64_events, cc64_times, start, end)
    write_ground_truth_midi(output_dir / f"{name}.mid", gt_notes, gt_pedal)

    chosen_gain = None
    chosen_peak = None
    if render:
        render_pm = build_render_source(notes, all_ccs, all_bends, end)

        chosen_window = None
        chosen_channels = None
        for gain in GAIN_CANDIDATES:
            window, channels, peak_dbfs = render_window(render_pm, start, end, gain, work_dir)
            chosen_gain, chosen_window, chosen_channels, chosen_peak = gain, window, channels, peak_dbfs
            if peak_dbfs <= TARGET_PEAK_DBFS:
                break
        else:
            print(f"  warning: {name} still at {chosen_peak:.1f} dBFS at the lowest gain candidate {chosen_gain}")

        write_wav(output_dir / f"{name}.wav", chosen_window, chosen_channels)

    return {
        "name": name,
        "notes": len(gt_notes),
        "gain": chosen_gain,
        "peak_dbfs": chosen_peak,
        "start": start,
        "midi_filename": midi_filename,
        "audio_filename": audio_filename,
    }


def select_and_process(output_dir, render=True, log=True):
    """The deterministic seed walk shared by rendering and manifest-only runs: same survey, same
    stratification, same per-bucket rng.sample, same per-case excerpt pick, in that exact order,
    so any two calls with the same `render` value at the same SEED produce the same cases and the
    same ground-truth <name>.mid files. Returns the per-case result dicts (see process_case).
    Importable directly (e.g. by make_real_audio_corpus.py) to run the walk in-process rather
    than through a CSV manifest round-trip.
    """

    def p(*a):
        if log:
            print(*a)

    p("surveying test-split pedal density...")
    candidates = survey_test_split()
    buckets = stratify(candidates)

    rng = random.Random(SEED)
    results = []

    with tempfile.TemporaryDirectory(prefix="maestro_render_") as tmp:
        work_dir = pathlib.Path(tmp)
        for bucket in BUCKET_NAMES:
            pool = sorted(buckets[bucket], key=lambda c: c.midi_filename)
            chosen = rng.sample(pool, PER_BUCKET) if len(pool) > PER_BUCKET else list(pool)
            if len(chosen) < PER_BUCKET:
                p(f"  note: bucket {bucket} has only {len(chosen)} candidates (< {PER_BUCKET}); using all of them")
            chosen.sort(key=lambda c: c.midi_filename)

            for idx, cand in enumerate(chosen, start=1):
                short_id = hashlib.sha1(cand.midi_filename.encode("utf-8")).hexdigest()[:4]
                name = f"maestro_{bucket}{idx}_{cand.year}_{short_id}"
                p(f"[{bucket}{idx}/{len(chosen)}] {name}  <- {cand.midi_filename}")
                result = process_case(name, cand.midi_filename, cand.audio_filename, rng, work_dir, output_dir, render=render)
                if result:
                    result["bucket"] = bucket
                    results.append(result)
                    if render:
                        p(f"    {result['notes']} gt notes, gain {result['gain']}, peak {result['peak_dbfs']:.1f} dBFS")
                    else:
                        p(f"    {result['notes']} gt notes, start {result['start']:.3f}s")

    p(f"\nwrote {len(results)} pairs to {output_dir}")
    for bucket in BUCKET_NAMES:
        count = sum(1 for r in results if r["bucket"] == bucket)
        p(f"  {bucket}: {count}")
    if results:
        note_counts = sorted(r["notes"] for r in results)
        mid = note_counts[len(note_counts) // 2]
        p(f"  notes per case: min {note_counts[0]}, median {mid}, max {note_counts[-1]}")

    return results


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("output", nargs="?", type=pathlib.Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--manifest",
        type=pathlib.Path,
        default=None,
        help=(
            "write the deterministic selection (name, bucket, source midi_filename, source "
            "audio_filename, window start seconds, gt note count) as a CSV to this path, and "
            "skip FluidSynth rendering entirely. Ground-truth <name>.mid files are still written "
            "to `output`, so a manifest run doubles as a determinism check: same seed walk, same "
            "picks, same mids, without touching audio."
        ),
    )
    arguments = parser.parse_args()
    render = arguments.manifest is None

    if not MAESTRO_CSV.exists():
        raise SystemExit(f"{MAESTRO_CSV} not found; run tools/bench/fetch_maestro.py first")

    arguments.output.mkdir(parents=True, exist_ok=True)
    if render:
        print(f"fluidsynth: {FLUIDSYNTH_EXE}")
        print(f"soundfont:  {SOUNDFONT}")
    else:
        print("manifest mode: skipping FluidSynth rendering")
    print(f"output:     {arguments.output}\n")

    results = select_and_process(arguments.output, render=render)

    if arguments.manifest is not None:
        arguments.manifest.parent.mkdir(parents=True, exist_ok=True)
        with open(arguments.manifest, "w", newline="", encoding="utf-8") as f:
            writer = csv.writer(f)
            writer.writerow(["name", "bucket", "midi_filename", "audio_filename", "start_seconds", "notes"])
            for r in results:
                writer.writerow([r["name"], r["bucket"], r["midi_filename"], r["audio_filename"], f"{r['start']:.6f}", r["notes"]])
        print(f"\nwrote manifest ({len(results)} rows) to {arguments.manifest}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
